# Import

In [3]:
import re

import pandas as pd
import numpy as np

# Init

In [4]:
people = [
    'N2N0',
    'ThenerB',
    'Dina B',
    'Terry L.',
    'Sjr',
    'HippyHippyShake',
    'Heavy Metal Zebra',
    'Tatami',
    'JustRimmey',
    'Matthew J. Hobbs',
    'Mooly',
    'JJdaPanda',
    'Duncan Moreland',
    'Marina',
    'rena :)',
    'EJ Gunter',
    'JacAttac',
    'Kate Booth',
    'Corgi'
]

# Read data

In [6]:
with open('output/260321_scraped_pages.csv', 'r', encoding = 'utf-8') as f:
    data = f.read()

data2 = data.split('\n\n\n\n\n\n\n')[1:]
data2

['+13\n12\nROUNDS\n  1\nSONG/ROUND\n  20 / 21\nPLAYERS\nRounds\nStandings\nChat\nROUND 10\nhappy birthday to youuuu\nsongs from the year you were born !! (maybe even the same month if you wanna deep dive that far)\nHide comments\nMy song(s)\nMy Own Worst Enemy\nLit\nA Place In The Sun\nfrom Spotify\n34\n13 voters\n1st\nN2N0\nThis was released exacrly on the day I was born\nMarina\n6\nThenerB\nBonus points for your specificity!\n5\nrena :)\n5\nJustRimmey\n3\nSjr\n3\nJacAttac\n2\nMatthew J. Hobbs\n2\nHippyHippyShake\n2\nTatami\n2\nJJdaPanda\n1\nHeavy Metal Zebra\n1\nTerry L.\n1\nDuncan Moreland\n1\nNever Gonna Give You Up\nRick Astley\nWhenever You Need Somebody\nfrom Spotify\n30\n12 voters\n2nd\nSjr\n1987\nMooly\n5\nrena :)\n4\nHeavy Metal Zebra\n3\nN2N0\n3\nMatthew J. Hobbs\n3\nTerry L.\n3\nJJdaPanda\n2\nThenerB\n2\nJacAttac\n2\nTatami\n1\nDuncan Moreland\n1\nJustRimmey\n1\nEverybody Wants To Rule The World\nTears For Fears\nSongs From The Big Chair (Super Deluxe Edition)\nfrom Spotify\n29\n13 voters\n3rd\nHippyHippyShake\nBorn is 1985 and this song is STILL a favorite of mine.\nMooly\n5\nN2N0\n3\nTerry L.\n3\nSjr\n2\nHeavy Metal Zebra\n2\nJJdaPanda\n2\nrena :)\n2\nJustRimmey\n2\nJacAttac\n2\nTatami\n2\nThenerB\n2\nMarina\n1\nDuncan Moreland\n1\nKiss\nPrince\nParade - Music from the Motion Picture Under the Cherry Moon\nfrom Spotify\n27\n13 voters\n4th\nThenerB\n😘\nHippyHippyShake\n4\nMooly\n4\nSjr\n2\nN2N0\n2\nrena :)\n2\nJustRimmey\n2\nHeavy Metal Zebra\n2\nJJdaPanda\n2\nTatami\n2\nDuncan Moreland\n2\nMatthew J. Hobbs\n1\nJacAttac\n1\nTerry L.\n1\nWelcome To The Jungle\nGuns N\' Roses\nAppetite For Destruction\nfrom Spotify\n26\n12 voters\n5th\nMooly\nYou know where you are? You\'re in the jungle, baby!\n\nHell yeah, bruther\nrena :)\n5\nHeavy Metal Zebra\n3\nDuncan Moreland\n3\nTerry L.\n3\nJJdaPanda\n2\nN2N0\n2\nJacAttac\n2\nMatthew J. Hobbs\n2\nTatami\n1\nSjr\n1\nJustRimmey\n1\nMarina\n1\nWithout Me\nEminem\nThe Eminem Show\nfrom Spotify\n25\n14 voters\n6th\nrena :)\n2002 ⭐️\nHippyHippyShake\n4\nHeavy Metal Zebra\n3\nTatami\n2\nDuncan Moreland\n2\nMarina\n2\nJustRimmey\n2\nMooly\n2\nTerry L.\n2\nJJdaPanda\n1\nN2N0\n1\nJacAttac\n1\nMatthew J. Hobbs\n1\nSjr\n1\nThenerB\n1\nPepper\nButthole Surfers\nElectriclarryland\nfrom Spotify\n24\n9 voters\n7th\nMarina\n1996\nMooly\n5\nJustRimmey\n4\nDuncan Moreland\nMy dad went to school with these guys\n3\nThenerB\n3\nMatthew J. Hobbs\n3\nTatami\n2\nSjr\n2\nJJdaPanda\n1\nJacAttac\n1\nKung Fu Fighting\nCarl Douglas\nKung Fu Fighter\nfrom Spotify\n22\n13 voters\n8th\nMatthew J. Hobbs\nMarina\n3\nN2N0\n3\nJJdaPanda\n3\nJustRimmey\n2\nJacAttac\n2\nTerry L.\n2\nHeavy Metal Zebra\n1\nTatami\n1\nDuncan Moreland\n1\nThenerB\n1\nrena :)\n1\nMooly\n1\nSjr\n1\nWhen Doves Cry\nPrince\nPurple Rain\nfrom Spotify\n22\n12 voters\n9th\nJustRimmey\nApril, 1984\nHippyHippyShake\n4\nTatami\n2\nSjr\n2\nDuncan Moreland\n2\nJacAttac\n2\nMatthew J. Hobbs\n2\nTerry L.\n2\nMarina\n2\nJJdaPanda\n1\nHeavy Metal Zebra\n1\nN2N0\n1\nThenerB\n1\nTorn\nNatalie Imbruglia\nLeft Of The Middle\nfrom Spotify\n20\n12 voters\n10th\nJacAttac\n97\nThenerB\n3\nHippyHippyShake\n2\nTatami\n2\nSjr\n2\nJustRimmey\n2\nMatthew J. Hobbs\n2\nTerry L.\n2\nJJdaPanda\n1\nHeavy Metal Zebra\n1\nN2N0\n1\nrena :)\n1\nMarina\n1\nDirty Diana\nMichael Jackson\nNumber Ones\nfrom Spotify\n15\n8 voters\n11th\nTatami\nJJdaPanda\n2\nHeavy Metal Zebra\n2\nHippyHippyShake\n2\nDuncan Moreland\nMichael Jackson the experience dancing game\n2\nrena :)\n2\nJacAttac\n2\nTerry L.\n2\nSjr\n1\nWhere Is The Love?\nBlack Eyed Peas\nElephunk\nfrom Spotify\n13\n8 voters\n12th\nJJdaPanda\n2003\nMatthew J. Hobbs\n3\nN2N0\n2\nrena :)\n2\nJacAttac\n2\nHeavy Metal Zebra\n1\nTatami\n1\nSjr\n1\nDuncan Moreland\n1\nBorn to Run\nBruce Springsteen\nBorn To Run\nfrom Spotify\n12\n8 voters\n13th\nTerry L.\n1975\nN2N0\n3\nMatthew J. Hobbs\n3\nJJdaPanda\n1\nHeavy Metal Zebra\n1\nTatami\n1\nSjr\n1\nJacAttac\n1\nMarina\n1\n505\nArctic Monkeys\nFavourite Worst Nightmare (Standard Version)\nfrom Spotify\n10\n7 voters\n14th\nDuncan Moreland\nN2N0\n2\nJacAttac\n2\nMarina\n2\nJJdaPanda\n1\nTatami\n1\nSjr\n1\nThenerB\n1\nLambada - Original Version 1989\nKaoma\nLambada - Les originaux No. 1 de l\'été (Original 1989)\nfrom Spotify\n8\n6 voters\n15th\nHeavy Metal Zebra\nDuncan Moreland\n2\nMarina\n2\nJJdaPanda\n1\nTatami\n1\nSjr\n1\nThenerB\n1\nSo Fresh, So Clean\nOutkast\nStankonia\nfrom Spotify\n24 0\n11 voters\n16th\nEJ Gunter\nDid not vote\nHippyHippyShake\n6\nJustRimmey\n3\nMarina\n3\nTatami\n2\nDuncan Moreland\n2\nThenerB\n2\nMooly\n2\nJJdaPanda\n1\nHeavy Metal Zebra\n1\nSjr\n1\nJacAttac\n1\nWe Built This City\nStarship\nKnee Deep In The Hoopla\nfrom Spotify\n19 0\n11 voters\n17th\nKate Booth\nDid not vote\n#1 the day I was born 😃\nTerry L.\n3\nJJdaPanda\n2\nHeavy Metal Zebra\n2\nSjr\n2\nThenerB\n2\nJustRimmey\n2\nMatthew J. Hobbs\n2\nTatami\n1\nN2N0\n1\nDuncan Moreland\n1\nJacAttac\n1"\nhttps://app.musicleague.com/l/fe4049a5bec34a9892e2fd5135a35ad3/33e1aa10943b48f29efad83a0fd600ae/,"OPEN\nSPEEDY\nall bangers all the time ✨\na speedy set full of fun catergories so we can all share our favorite bangers ◡̈\n\nAdmin',
 '+13\n12\nROUNDS\n  1\nSONG/ROUND\n  20 / 21\nPLAYERS\nRounds\nStandings\nChat\nROUND 9\ngone solo\nfavorite song from an artist who started in a band but have since had a solo career\nHide comments\nMy song(s)\nEdge of Seventeen\nStevie Nicks\nCrystal Visions...The Very Best of Stevie Nicks\nfrom Spotify\n48\n16 voters\n1st\nDina B\nMarina\n6\nMooly\n5\nHippyHippyShake\n5\nEJ Gunter\nValid choice🤞🏾\n5\nMatthew J. Hobbs\n5\nN2N0\n4\nKate Booth\n3\nTerry L.\n3\nrena :)\n3\nHeavy Metal Zebra\n2\nTatami\n2\nJJdaPanda\n1\nSjr\n1\nDuncan Moreland\n1\nThenerB\nWell played \n1\nJustRimmey\n1\nCrazy Train\nOzzy Osbourne\nBlizzard Of Ozz (40th Anniversary Expanded Edition)\nfrom Spotify\n35\n15 voters\n2nd\nMatthew J. Hobbs\nrena :)\n6\nDuncan Moreland\n4\nHeavy Metal Zebra\n4\nDina B\n3\nTerry L.\n3\nSjr\n2\nTatami\n2\nEJ Gunter\n2\nMarina\n2\nMooly\n2\nJJdaPanda\n1\nKate Booth\n1\nJustRimmey\n1\nThenerB\n1\nN2N0\n1\nDoo Wop (That Thing)\nMs. Lauryn Hill\nThe Miseducation of Lauryn Hill\nfrom Spotify\n35\n15 voters\n3rd\nKate Booth\nHippyHippyShake\n5\nMatthew J. Hobbs\n4\nEJ Gunter\n4\nJustRimmey\n3\nSjr\n3\nThenerB\nOmg The Fugees, didn’t even think about it! Great pick \n3\nTerry L.\n2\nTatami\n2\nDina B\n2\nMarina\n2\nJJdaPanda\n1\nHeavy Metal Zebra\n1\nrena :)\n1\nN2N0\n1\nDuncan Moreland\n1\nIn The Air Tonight - 2015 Remastered\nPhil Collins\nFace Value (Deluxe Editon)\nfrom Spotify\n33\n14 voters\n4th\nJustRimmey\nStarted in Genesis\nHeavy Metal Zebra\n5\nMooly\n5\nMatthew J. Hobbs\n4\nTerry L.\n3\nN2N0\n3\nEJ Gunter\n3\nTatami\n2\nKate Booth\n2\nJJdaPanda\n1\nrena :)\n1\nThenerB\n1\nDuncan Moreland\n1\nDina B\n1\nSjr\n1\nThem Changes\nThundercat\nDrunk\nfrom Spotify\n28\n12 voters\n5th\nTatami\nMarina\n5\nKate Booth\n4\nHippyHippyShake\n3\nDuncan Moreland\n3\nEJ Gunter\n3\nDina B\n2\nJustRimmey\n2\nMooly\n2\nJJdaPanda\n1\nHeavy Metal Zebra\n1\nSjr\n1\nThenerB\nCool!\n1\nSledgehammer - 2012 Remaster\nPeter Gabriel\nSo (25th Anniversary Deluxe Edition)\nfrom Spotify\n28\n12 voters\n6th\nN2N0\nMooly\n5\nKate Booth\n3\nHeavy Metal Zebra\n3\nJustRimmey\nGod those horns are glorious!!\n3\nTerry L.\n3\nTatami\n2\nSjr\n2\nDuncan Moreland\n2\nMatthew J. Hobbs\n2\nJJdaPanda\n1\nDina B\n1\nThenerB\n1\nBeat It\nMichael Jackson\nThriller\nfrom Spotify\n27\n12 voters\n7th\nSjr\nHeavy Metal Zebra\n4\nDuncan Moreland\n4\nHippyHippyShake\n3\nMatthew J. Hobbs\n3\nTerry L.\n3\nTatami\n2\nMooly\n2\nEJ Gunter\n2\nJJdaPanda\n1\nDina B\n1\nThenerB\nDidn’t even think of MJ, well played \n1\nMarina\n1\nSexyBack (feat. Timbaland)\nJustin Timberlake\nFutureSex/LoveSounds\nfrom Spotify\n24\n13 voters\n8th\nDuncan Moreland\nrena :)\n4\nTatami\n4\nEJ Gunter\n3\nMarina\n2\nN2N0\n2\nJustRimmey\n2\nKate Booth\n1\nJJdaPanda\n1\nHeavy Metal Zebra\n1\nTerry L.\n1\nSjr\n1\nThenerB\n1\nDina B\n1\nThe Heart Of The Matter\nDon Henley\nThe End Of The Innocence\nfrom Spotify\n23\n11 voters\n9th\nTerry L.\nFrom the band The Eagles\nN2N0\n4\nMatthew J. Hobbs\n4\nDina B\n3\nHeavy Metal Zebra\n2\nSjr\n2\nrena :)\n2\nJustRimmey\n2\nJJdaPanda\n1\nTatami\n1\nDuncan Moreland\n1\nThenerB\n1\nAPT.\nROSÉ\nrosie\nfrom Spotify\n21\n9 voters\n10th\nThenerB\nHippyHippyShake\n5\nJJdaPanda\n4\nMooly\n3\nTatami\n2\nJustRimmey\n2\nMarina\n2\nSjr\n1\nDina B\n1\nMatthew J. Hobbs\n1\nTwist Of Cain\nDanzig\nDanzig\nfrom Spotify\n17\n8 voters\n11th\nMooly\nPreviously of the Misfits\nKate Booth\n5\nJustRimmey\n4\nDuncan Moreland\n3\nJJdaPanda\n1\nHeavy Metal Zebra\n1\nSjr\n1\nDina B\n1\nThenerB\n1\nBeautiful Dangerous (feat. Fergie)\nSlash\nSlash (Special Edition)\nfrom Spotify\n16\n10 voters\n12th\nHeavy Metal Zebra\nDuncan Moreland\n3\nTerry L.\n3\nDina B\n2\nrena :)\n2\nJJdaPanda\n1\nSjr\n1\nN2N0\n1\nThenerB\nPoint for the twofer\n1\nJustRimmey\n1\nMarina\n1\nSlow Hands\nNiall Horan\nFlicker (Deluxe)\nfrom Spotify\n16\n8 voters\n13th\nrena :)\nHippyHippyShake\n3\nSjr\n3\nN2N0\n3\nKate Booth\n2\nJJdaPanda\n2\nTatami\n1\nDina B\n1\nThenerB\n1\nlike JENNIE\nJENNIE\nRuby\nfrom Spotify\n13\n6 voters\n14th\nHippyHippyShake\nTry not to dance challenge lvl Impossible\nJJdaPanda\n3\nMarina\n3\nTatami\n2\nThenerB\nGreat minds think alike - BLACKPINK in your area!\n2\nJustRimmey\n2\nDina B\n1\nDuncan Moreland\nFr?\nPILLOWTALK\nZAYN\nMind Of Mine (Deluxe Edition)\nfrom Spotify\n11\n7 voters\n15th\nEJ Gunter\nrena :)\n3\nKate Booth\n2\nN2N0\n2\nJJdaPanda\n1\nSjr\n1\nDina B\n1\nThenerB\n1\nmirror\nMoon Byul\nDark Side of the Moon\nfrom Spotify\n7\n6 voters\n16th\nMarina\nMoon Byul is a former member of K-pop group MAMAMOO\nThenerB\nLove MAMAMOO and more kpop on here!\n2\nJJdaPanda\n1\nTatami\n1\nSjr\n1\nDina B\n1\nJustRimmey\n1\nBorn With a Broken Heart\nDamiano David\nFUNNY little FEARS\nfrom Spotify\n6\n5 voters\n17th\nJJdaPanda\nSjr\n2\nKate Booth\n1\nTatami\n1\nDina B\n1\nThenerB\nNice!\n1\nAdore You\nHarry Styles\nFine Line\nfrom Spotify\n20 0\n10 voters\n18th\nJacAttac\nDid not vote\nThenerB\nHarry was my first pick, beat me to it 💛\n4\nN2N0\n3\nTerry L.\n3\nJJdaPanda\n2\nrena :)\n2\nEJ Gunter\n2\nSjr\n1\nDuncan Moreland\n1\nDina B\n1\nMatthew J. Hobbs\n1"\nhttps://app.musicleague.com/l/fe4049a5bec34a9892e2fd5135a35ad3/5bd2afdcac554efeb2351d1012e3b9ee/,"OPEN\nSPEEDY\nall bangers all the time ✨\na speedy set full of fun catergories so we can all share our favorite bangers ◡̈\n\nAdmin',
 '+13\n12\nROUNDS\n  1\nSONG/ROUND\n  20 / 21\nPLAYERS\nRounds\nStandings\nChat\nROUND 8\ntitle containing punctuation\nEX : when did you get hot ? sabrina carpenter\nanything from ? to , count\nHide comments\nMy song(s)\nWhere Is My Mind?\nPixies\nDeath to the Pixies\nfrom Spotify\n41\n12 voters\n1st\nKate Booth\nMooly\n7\nHeavy Metal Zebra\n5\nMatthew J. Hobbs\n5\nHippyHippyShake\n4\nMarina\n4\nN2N0\n3\nDuncan Moreland\n3\nThenerB\nForgot about this song 👍👍\n3\nJustRimmey\n3\nSjr\n2\nJJdaPanda\n1\nJacAttac\n1\nbad idea right?\nOlivia Rodrigo\nGUTS\nfrom Spotify\n37\n12 voters\n2nd\nJJdaPanda\nHippyHippyShake\n6\nDuncan Moreland\n4\nJacAttac\n4\nTerry L.\n4\nMarina\n4\nHeavy Metal Zebra\n3\nN2N0\n3\nKate Booth\n2\nThenerB\nFelt lol\n2\nJustRimmey\n2\nMatthew J. Hobbs\n2\nSjr\n1\nHey Ya!\nOutkast\nSpeakerboxxx/The Love Below\nfrom Spotify\n36\n13 voters\n3rd\nDuncan Moreland\nHippyHippyShake\n6\nHeavy Metal Zebra\n5\nKate Booth\n4\nJacAttac\n4\nMatthew J. Hobbs\n4\nN2N0\n3\nTerry L.\n2\nThenerB\n2\nJustRimmey\n2\nJJdaPanda\n1\nMooly\n1\nMarina\n1\nSjr\n1\nDa Ya Think I\'m Sexy?\nRod Stewart\nBlondes Have More Fun\nfrom Spotify\n29\n12 voters\n4th\nTerry L.\nMooly\n8\nKate Booth\n4\nHeavy Metal Zebra\n3\nThenerB\nNice throwback \n3\nSjr\n2\nJustRimmey\n2\nMatthew J. Hobbs\n2\nJJdaPanda\n1\nN2N0\n1\nDuncan Moreland\n1\nJacAttac\n1\nMarina\n1\nAin\'t It Fun\nParamore\nParamore (Deluxe Edition)\nfrom Spotify\n26\n11 voters\n5th\nHippyHippyShake\nForever a Hayley Williams fan\nJustRimmey\n4\nTerry L.\n4\nKate Booth\n3\nHeavy Metal Zebra\n3\nN2N0\n3\nDuncan Moreland\n3\nSjr\n2\nJJdaPanda\n1\nThenerB\nI can’t not give a vote for this song \n1\nMatthew J. Hobbs\n1\nMarina\n1\nHOT TO GO!\nChappell Roan\nThe Rise and Fall of a Midwest Princess\nfrom Spotify\n25\n10 voters\n6th\nMooly\nMarina\n6\nTerry L.\n4\nJacAttac\n3\nMatthew J. Hobbs\n3\nN2N0\n2\nDuncan Moreland\n2\nJustRimmey\n2\nJJdaPanda\n1\nSjr\n1\nThenerB\n1\nWhy\'d You Only Call Me When You\'re High?\nArctic Monkeys\nAM\nfrom Spotify\n23\n10 voters\n7th\nN2N0\nJacAttac\n4\nMooly\n4\nDuncan Moreland\n3\nMarina\n3\nSjr\n2\nThenerB\nClassic\n2\nJustRimmey\n2\nJJdaPanda\n1\nMatthew J. Hobbs\n1\nTerry L.\n1\nWHERE IS MY HUSBAND!\nRAYE\nWHERE IS MY HUSBAND!\nfrom Spotify\n23\n9 voters\n8th\nJacAttac\nJJdaPanda\n5\nDuncan Moreland\n4\nTerry L.\n3\nMarina\n3\nHeavy Metal Zebra\n2\nSjr\n2\nN2N0\n2\nThenerB\n1\nMatthew J. Hobbs\n1\n(What\'s So Funny \'Bout) Peace, Love And Understanding\nElvis Costello & The Attractions\nArmed Forces (Super Deluxe Edition)\nfrom Spotify\n21\n11 voters\n9th\nMatthew J. Hobbs\nParentheses-Apostrophe-Commas\n Take your pick\nKate Booth\n4\nSjr\n3\nHeavy Metal Zebra\n2\nHippyHippyShake\n2\nJustRimmey\n2\nMooly\n2\nTerry L.\n2\nJJdaPanda\n1\nN2N0\n1\nThenerB\n1\nJacAttac\n1\nSPOT!\nZICO\nSPOT!\nfrom Spotify\n18\n11 voters\n10th\nThenerB\nJJdaPanda\n4\nN2N0\n3\nDuncan Moreland\n2\nMooly\n2\nKate Booth\n1\nSjr\n1\nJustRimmey\n1\nJacAttac\n1\nMatthew J. Hobbs\n1\nTerry L.\n1\nMarina\n1\nInjustice System!\nSick Of It All\nNonstop\nfrom Spotify\n17\n10 voters\n11th\nHeavy Metal Zebra\nHippyHippyShake\n4\nKate Booth\n3\nSjr\n2\nJustRimmey\n2\nJJdaPanda\n1\nN2N0\n1\nDuncan Moreland\n1\nThenerB\n1\nJacAttac\n1\nMatthew J. Hobbs\n1\nBang!\nAJR\nOK ORCHESTRA\nfrom Spotify\n16\n8 voters\n12th\nSjr\nJJdaPanda\n5\nThenerB\nLove this song, underrated \n3\nJacAttac\n2\nTerry L.\n2\nKate Booth\n1\nHippyHippyShake\n1\nN2N0\n1\nMatthew J. Hobbs\n1\nicarus?\nserin oh\nicarus?\nfrom Spotify\n15\n11 voters\n13th\nMarina\nKate Booth\n2\nSjr\n2\nThenerB\nNever heard it but like it\n*also reminds me of Super Cool from the 2nd Lego movie and I can’t I hear it \n2\nJustRimmey\n2\nJJdaPanda\n1\nHeavy Metal Zebra\n1\nN2N0\n1\nDuncan Moreland\n1\nJacAttac\n1\nMatthew J. Hobbs\n1\nTerry L.\n1\nOxford Comma\nVampire Weekend\nVampire Weekend\nfrom Spotify\n9\n6 voters\n14th\nJustRimmey\nThe name being a style of a comma has to work right?\nSjr\n3\nThenerB\nNormally I would not count this but appreciate the creativity and give a f*ck about an Oxford comma (and I love this song so much lol) \n2\nJJdaPanda\n1\nHippyHippyShake\n1\nJacAttac\n1\nMatthew J. Hobbs\n1"\nhttps://app.musicleague.com/l/fe4049a5bec34a9892e2fd5135a35ad3/9f17eca5e0634b01972f4ae343ed6b85/,"OPEN\nSPEEDY\nall bangers all the time ✨\na speedy set full of fun catergories so we can all share our favorite bangers ◡̈\n\nAdmin',

# Data proc

## Proc 1

In [8]:
for index, row0 in enumerate(data2):
    # row0 = data2[0]
    row1 = '\n'.join(row0.split('\n')[15:])

    round_info = row0.split('\n')[10:13]

    songs = [
        i.strip()
        for i in '\n'.join(row0.split('\n')[15:]).split('from Spotify')]
    songs
    songs_names = [songs[0]] + ['\n'.join(i.split('\n')[-3:]) for i in songs[1:-1]]
    songs_names
    songs_votes_voters_rank_person = [
        '\n'.join(i.split('\n')[:4])
        for i in songs[1:]
    ]
    songs_votes_voters_rank_person
    votes_and_comments = [
        '\n'.join(i.split('\n')[4:-3])
        for i in songs[1:]
    ]
    votes_and_comments = [i for i in votes_and_comments[:-1]] + \
        ['\n'.join(votes_and_comments[-1].split('\n')[:-2])]
    votes_and_comments
    votes_and_comments2 = [
        i if i.split('\n')[0] in people else '\n'.join(i.split('\n')[1:])
        for i in votes_and_comments
    ]
    votes_and_comments2
    '|'.join(people)
    person_submit_comments = [
        '' if i.split('\n')[0] in people else i.split('\n')[0]
        for i in votes_and_comments
    ]
    person_submit_comments

    songs
    songs_votes_voters_rank_person
    df_round = pd.DataFrame({
        'Round': round_info[0],
        'Round name': round_info[1],
        'Round description': round_info[2],
        'Song name': songs_names,
        'Song votes':                    [i.split('\n')[0] for i in songs_votes_voters_rank_person],
        'Song voters':                   [i.split('\n')[1] for i in songs_votes_voters_rank_person],
        'Song rank':                     [i.split('\n')[2] for i in songs_votes_voters_rank_person],
        'Song person submitted':         [i.split('\n')[3] for i in songs_votes_voters_rank_person],
        'Song person submitted comment': person_submit_comments,
        'Votes and comments':            votes_and_comments2
    })

    if index == 0:
        df_overall = df_round
    else:
        df_overall = pd.concat(
            [df_overall, df_round], 
            axis = 'rows',
            sort = False
        )

In [9]:
df_overall

,Round,Round name,Round description,Song name,Song votes,Song voters,Song rank,Song person submitted,Song person submitted comment,Votes and comments
0,ROUND 10,happy birthday to youuuu,songs from the year you were born !! (maybe ev...,My Own Worst Enemy\nLit\nA Place In The Sun,34,13 voters,1st,N2N0,This was released exacrly on the day I was born,Marina\n6\nThenerB\nBonus points for your spec...
1,ROUND 10,happy birthday to youuuu,songs from the year you were born !! (maybe ev...,Never Gonna Give You Up\nRick Astley\nWhenever...,30,12 voters,2nd,Sjr,1987,Mooly\n5\nrena :)\n4\nHeavy Metal Zebra\n3\nN2...
2,ROUND 10,happy birthday to youuuu,songs from the year you were born !! (maybe ev...,Everybody Wants To Rule The World\nTears For F...,29,13 voters,3rd,HippyHippyShake,Born is 1985 and this song is STILL a favorite...,Mooly\n5\nN2N0\n3\nTerry L.\n3\nSjr\n2\nHeavy ...
3,ROUND 10,happy birthday to youuuu,songs from the year you were born !! (maybe ev...,Kiss\nPrince\nParade - Music from the Motion P...,27,13 voters,4th,ThenerB,😘,HippyHippyShake\n4\nMooly\n4\nSjr\n2\nN2N0\n2\...
4,ROUND 10,happy birthday to youuuu,songs from the year you were born !! (maybe ev...,Welcome To The Jungle\nGuns N' Roses\nAppetite...,26,12 voters,5th,Mooly,"You know where you are? You're in the jungle, ...","\nHell yeah, bruther\nrena :)\n5\nHeavy Metal ..."
...,...,...,...,...,...,...,...,...,...,...
16,ROUND 1,name in the title,"girls name, guys name, singers name, youuuu na...",Bella\nAIDAN\nBella,13,9 voters,17th,Corgi,,HippyHippyShake\n3\nMarina\n3\nJJdaPanda\n1\nH...
17,ROUND 1,name in the title,"girls name, guys name, singers name, youuuu na...",Justin's Headed Out\nmercury\nJustin's Headed Out,13,7 voters,18th,[Left the league],,Duncan Moreland\n3\nTerry L.\n3\nMarina\n3\n[L...
18,ROUND 1,name in the title,"girls name, guys name, singers name, youuuu na...",Evangeline\nStephen Sanchez\nEvangeline,13,6 voters,19th,N2N0,[Left the league],4\nTerry L.\n3\nDina B\n2\nMooly\n2\nJJdaPanda...
19,ROUND 1,name in the title,"girls name, guys name, singers name, youuuu na...",Velvet Elvis\nKacey Musgraves\nGolden Hour,11,9 voters,20th,HippyHippyShake,,JacAttac\n2\nTerry L.\n2\nSjr\n1\n[Left the le...
20,ROUND 1,name in the title,"girls name, guys name, singers name, youuuu na...",Bobby James\nN.E.R.D\nIn Search Of...,10,10 voters,21st,[Left the league],,Tatami\n1\nSjr\n1\n[Left the league]\n1\nN2N0\...

In [11]:
df_overall.to_csv('output/2_processed_data/260321_proc_data_1.csv', index = False)

## Proc 2

Trim some fields and separate the field `Song name` into `Song`, `Artist`, and `Album`

In [20]:
df_overall_2 = df_overall.copy(deep = True)

df_overall_2['Round'] = df_overall_2['Round'].apply(
    lambda x: x.split(' ')[-1]
)

df_overall_2['Song name'] = df_overall_2['Song name'].str.strip('My song(s)\n')

df_overall_2[['Song', 'Artist', 'Album']] = df_overall_2['Song name'].str.split('\n', expand = True)
df_overall_2 = df_overall_2.drop(columns = ['Song name'])

df_overall_2['Song voters'] = df_overall_2['Song voters'].apply(
    lambda x: x.split(' ')[0]
)

df_overall_2 = df_overall_2[[
    'Round', 'Round name', 'Round description', 
    'Song', 'Artist', 'Album',
    'Song votes', 'Song voters', 'Song rank', 'Song person submitted', 'Song person submitted comment',
    'Votes and comments'
    ]]

df_overall_2

,Round,Round name,Round description,Song,Artist,Album,Song votes,Song voters,Song rank,Song person submitted,Song person submitted comment,Votes and comments
0,10,happy birthday to youuuu,songs from the year you were born !! (maybe ev...,Own Worst Enemy,Lit,A Place In The Su,34,13,1st,N2N0,This was released exacrly on the day I was born,Marina\n6\nThenerB\nBonus points for your spec...
1,10,happy birthday to youuuu,songs from the year you were born !! (maybe ev...,Never Gonna Give You Up,Rick Astley,Whenever You Need Somebod,30,12,2nd,Sjr,1987,Mooly\n5\nrena :)\n4\nHeavy Metal Zebra\n3\nN2...
2,10,happy birthday to youuuu,songs from the year you were born !! (maybe ev...,Everybody Wants To Rule The World,Tears For Fears,Songs From The Big Chair (Super Deluxe Editi,29,13,3rd,HippyHippyShake,Born is 1985 and this song is STILL a favorite...,Mooly\n5\nN2N0\n3\nTerry L.\n3\nSjr\n2\nHeavy ...
3,10,happy birthday to youuuu,songs from the year you were born !! (maybe ev...,Kiss,Prince,Parade - Music from the Motion Picture Under t...,27,13,4th,ThenerB,😘,HippyHippyShake\n4\nMooly\n4\nSjr\n2\nN2N0\n2\...
4,10,happy birthday to youuuu,songs from the year you were born !! (maybe ev...,Welcome To The Jungle,Guns N' Roses,Appetite For Destructi,26,12,5th,Mooly,"You know where you are? You're in the jungle, ...","\nHell yeah, bruther\nrena :)\n5\nHeavy Metal ..."
...,...,...,...,...,...,...,...,...,...,...,...,...
16,1,name in the title,"girls name, guys name, singers name, youuuu na...",Bella,AIDAN,Bella,13,9,17th,Corgi,,HippyHippyShake\n3\nMarina\n3\nJJdaPanda\n1\nH...
17,1,name in the title,"girls name, guys name, singers name, youuuu na...",Justin's Headed Out,mercury,Justin's Headed Out,13,7,18th,[Left the league],,Duncan Moreland\n3\nTerry L.\n3\nMarina\n3\n[L...
18,1,name in the title,"girls name, guys name, singers name, youuuu na...",Evangeline,Stephen Sanchez,Evangeline,13,6,19th,N2N0,[Left the league],4\nTerry L.\n3\nDina B\n2\nMooly\n2\nJJdaPanda...
19,1,name in the title,"girls name, guys name, singers name, youuuu na...",Velvet Elvis,Kacey Musgraves,Golden Hour,11,9,20th,HippyHippyShake,,JacAttac\n2\nTerry L.\n2\nSjr\n1\n[Left the le...
20,1,name in the title,"girls name, guys name, singers name, youuuu na...",Bobby James,N.E.R.D,In Search Of...,10,10,21st,[Left the league],,Tatami\n1\nSjr\n1\n[Left the league]\n1\nN2N0\...

In [21]:
df_overall_2.to_csv('output/2_processed_data/260321_proc_data_2.csv', index = False)

## Proc 3

Final processing:
- Splitting the hardest column, `Votes and comments`, into row per individual person/comment in the long format.

In [23]:
def proc1(x):
    name_rest = ''

    for index, i in enumerate(x.split('\n')):
        # print(i)
        
        if i in people:
            name_rest += f"<br>{i}"
        else:
            name_rest += f"___{i}"
    
    name_rest = [
        i 
        for i in name_rest.split('<br>')
        if i
    ]
    return name_rest

In [24]:
def proc2(x):
    x2 = x.split('___')
    vote = [i for i in x2 if i.isdigit()]
    vote = '' if len(vote) == 0 else vote[0]
    
    comment = '___'.join([i for i in x2 if not i.isdigit()])
    comment = '' if not comment else comment
    return ':::'.join([vote, comment])

In [25]:
df_overall_3 = df_overall_2.copy(deep = True)

df_overall_3['Votes and comments'] = df_overall_3['Votes and comments'].apply(
    lambda x: proc1(x)
)
df_overall_3 = df_overall_3.explode('Votes and comments')

df_overall_3['person who voted'] = df_overall_3['Votes and comments'].apply(
    lambda x: x.split('___')[0]
)
df_overall_3['person who voted other'] = df_overall_3['Votes and comments'].apply(
    lambda x: '___'.join(x.split('___')[1:])
)

df_overall_3 = df_overall_3.drop('Votes and comments', axis = 1)

df_overall_3['person who voted other'] = df_overall_3['person who voted other'].apply(
    lambda x: proc2(x)
)
df_overall_3[['person who voted - vote', 'person who voted - comment']] = df_overall_3['person who voted other'].str.split(':::', expand = True)
df_overall_3 = df_overall_3.drop('person who voted other', axis = 1)

df_overall_3

,Round,Round name,Round description,Song,Artist,Album,Song votes,Song voters,Song rank,Song person submitted,Song person submitted comment,person who voted,person who voted - vote,person who voted - comment
0,10,happy birthday to youuuu,songs from the year you were born !! (maybe ev...,Own Worst Enemy,Lit,A Place In The Su,34,13,1st,N2N0,This was released exacrly on the day I was born,Marina,6,
0,10,happy birthday to youuuu,songs from the year you were born !! (maybe ev...,Own Worst Enemy,Lit,A Place In The Su,34,13,1st,N2N0,This was released exacrly on the day I was born,ThenerB,5,Bonus points for your specificity!
0,10,happy birthday to youuuu,songs from the year you were born !! (maybe ev...,Own Worst Enemy,Lit,A Place In The Su,34,13,1st,N2N0,This was released exacrly on the day I was born,rena :),5,
0,10,happy birthday to youuuu,songs from the year you were born !! (maybe ev...,Own Worst Enemy,Lit,A Place In The Su,34,13,1st,N2N0,This was released exacrly on the day I was born,JustRimmey,3,
0,10,happy birthday to youuuu,songs from the year you were born !! (maybe ev...,Own Worst Enemy,Lit,A Place In The Su,34,13,1st,N2N0,This was released exacrly on the day I was born,Sjr,3,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20,1,name in the title,"girls name, guys name, singers name, youuuu na...",Bobby James,N.E.R.D,In Search Of...,10,10,21st,[Left the league],,Duncan Moreland,1,
20,1,name in the title,"girls name, guys name, singers name, youuuu na...",Bobby James,N.E.R.D,In Search Of...,10,10,21st,[Left the league],,Dina B,1,
20,1,name in the title,"girls name, guys name, singers name, youuuu na...",Bobby James,N.E.R.D,In Search Of...,10,10,21st,[Left the league],,ThenerB,1,
20,1,name in the title,"girls name, guys name, singers name, youuuu na...",Bobby James,N.E.R.D,In Search Of...,10,10,21st,[Left the league],,JustRimmey,1,I want a new NERD album!
20,1,name in the title,"girls name, guys name, singers name, youuuu na...",Bobby James,N.E.R.D,In Search Of...,10,10,21st,[Left the league],,Matthew J. Hobbs,1,"[Left the league]___1""___""___""___""___""___=___=..."

In [26]:
df_overall_3.to_csv('output/2_processed_data/260321_proc_data_3.csv', index = False)

In [27]:
df_overall_3.to_excel('output/2_processed_data/260321_proc_data_3.xlsx', index = False)